In [152]:
import pandas as pd

In [153]:
mvps = pd.read_csv("mvps.csv")

In [154]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,8,9,Stephen Curry,34,GSW,0.0,5.0,1000,0.005,56,...,6.1,6.3,0.9,0.4,0.493,0.427,0.915,7.8,0.192,2023
495,9,10,Jimmy Butler,33,MIA,0.0,3.0,1000,0.003,64,...,5.9,5.3,1.8,0.3,0.539,0.350,0.850,12.3,0.277,2023
496,10,11,De'Aaron Fox,25,SAC,0.0,2.0,1000,0.002,73,...,4.2,6.1,1.1,0.3,0.512,0.324,0.780,7.4,0.146,2023
497,11,12T,Jalen Brunson,26,NYK,0.0,1.0,1000,0.001,68,...,3.5,6.2,0.9,0.2,0.491,0.416,0.829,8.7,0.175,2023
498,12,12T,Ja Morant,23,MEM,0.0,1.0,1000,0.001,61,...,5.9,8.1,1.1,0.3,0.466,0.307,0.748,6.0,0.148,2023

In [155]:
mvps = mvps[["Player", "Year", "Pts Won", "Pts Max", "Share"]]

In [156]:
mvps

              Player  Year  Pts Won  Pts Max  Share
0     Michael Jordan  1991    891.0      960  0.928
1      Magic Johnson  1991    497.0      960  0.518
2     David Robinson  1991    476.0      960  0.496
3    Charles Barkley  1991    222.0      960  0.231
4        Karl Malone  1991    142.0      960  0.148
..               ...   ...      ...      ...    ...
494    Stephen Curry  2023      5.0     1000  0.005
495     Jimmy Butler  2023      3.0     1000  0.003
496     De'Aaron Fox  2023      2.0     1000  0.002
497    Jalen Brunson  2023      1.0     1000  0.001
498        Ja Morant  2023      1.0     1000  0.001

[499 rows x 5 columns]

In [157]:
players = pd.read_csv("players.csv")

In [158]:
players

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19584,699,535,Thaddeus Young,PF,34,TOR,54,9,14.7,2.0,...,1.3,1.8,3.1,1.4,1.0,0.1,0.8,1.6,4.4,2023
19585,700,536,Trae Young,PG,24,ATL,73,73,34.8,8.2,...,0.8,2.2,3.0,10.2,1.1,0.1,4.1,1.4,26.2,2023
19586,701,537,Omer Yurtseven,C,24,MIA,9,0,9.2,1.8,...,0.9,1.7,2.6,0.2,0.2,0.2,0.4,1.8,4.4,2023
19587,702,538,Cody Zeller,C,30,MIA,15,2,14.5,2.5,...,1.7,2.6,4.3,0.7,0.2,0.3,0.9,2.2,6.5,2023
19588,703,539,Ivica Zubac,C,25,LAC,76,76,28.6,4.3,...,3.1,6.8,9.9,1.0,0.4,1.3,1.5,2.9,10.8,2023

In [159]:
del players["Unnamed: 0"]
del players["Rk"]

In [160]:
players

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19584,Thaddeus Young,PF,34,TOR,54,9,14.7,2.0,3.7,.545,...,1.3,1.8,3.1,1.4,1.0,0.1,0.8,1.6,4.4,2023
19585,Trae Young,PG,24,ATL,73,73,34.8,8.2,19.0,.429,...,0.8,2.2,3.0,10.2,1.1,0.1,4.1,1.4,26.2,2023
19586,Omer Yurtseven,C,24,MIA,9,0,9.2,1.8,3.0,.593,...,0.9,1.7,2.6,0.2,0.2,0.2,0.4,1.8,4.4,2023
19587,Cody Zeller,C,30,MIA,15,2,14.5,2.5,3.9,.627,...,1.7,2.6,4.3,0.7,0.2,0.3,0.9,2.2,6.5,2023
19588,Ivica Zubac,C,25,LAC,76,76,28.6,4.3,6.8,.634,...,3.1,6.8,9.9,1.0,0.4,1.3,1.5,2.9,10.8,2023

In [161]:
players["Player"] = players["Player"].str.replace("*", "", regex = False)

In [162]:
def single_row(df):
    if df.shape[0] == 1:
        return df
    else:
        row = df[df["Tm"] == "TOT"]
        row["Tm"] = df.iloc[-1, :]["Tm"]
        return row
    
players = players.groupby(["Player", "Year"]).apply(single_row)

In [163]:
players.head(20)

                                 Player Pos Age   Tm   G  GS    MP   FG   FGA  \
Player        Year
A.C. Green    1991 164       A.C. Green  PF  27  LAL  82  21  26.4  3.1   6.6
              1992 633       A.C. Green  PF  28  LAL  82  53  35.4  4.7   9.8
              1993 1092      A.C. Green  PF  29  LAL  82  55  34.4  4.6   8.6
              1994 1579      A.C. Green  PF  30  PHO  82  55  34.5  5.7  11.3
              1995 2067      A.C. Green  SF  31  PHO  82  52  32.8  3.8   7.5
              1996 2563      A.C. Green  SF  32  PHO  82  36  25.8  2.6   5.4
              1997 3138      A.C. Green  PF  33  DAL  83  73  30.0  2.8   5.8
              1998 3725      A.C. Green  PF  34  DAL  82  68  32.3  3.0   6.5
              1999 4283      A.C. Green  PF  35  DAL  50  35  18.5  2.2   5.1
              2000 4811      A.C. Green  PF  36  LAL  82  82  23.5  2.1   4.7
              2001 5330      A.C. Green  PF  37  MIA  82   1  17.2  1.8   4.0
A.J. Bramlett 2000 4684   A.J. Bramlett   C  23  CLE   8   0   7.6  0.5   2.6
A.J. English  1991 127     A.J. English  SG  23  WSB  70  12  20.6  3.6   8.2
              1992 597     A.J. English  SG  24  WSB  81   6  20.6  4.5  10.4
A.J. Green    2023 19115     A.J. Green  SG  23  MIL  35   1   9.9  1.5   3.6
A.J. Guyton   2001 5333     A.J. Guyton  PG  22  CHI  33   8  19.1  2.4   5.8
              2002 5886     A.J. Guyton  PG  23  CHI  45   6  13.5  2.0   5.4
              2003 6393     A.J. Guyton  PG  24  GSW   2   0   4.5  0.0   2.0
A.J. Hammons  2017 14814   A.J. Hammons   C  24  DAL  22   0   7.4  0.8   1.9
A.J. Lawson   2023 19259    A.J. Lawson  SG  22  DAL  15   0   7.2  1.5   2.9

                           FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  \
Player        Year              ...
A.C. Green    1991 164    .476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2  1.4
              1992 633    .476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4  1.7
              1993 1092   .537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4  1.8
              1994 1579   .502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2  1.7
              1995 2067   .504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4  1.8
              1996 2563   .484  ...  2.0  4.7  6.8  0.9  0.5  0.3  1.0  1.7
              1997 3138   .483  ...  2.7  5.2  7.9  0.8  0.8  0.2  0.9  1.7
              1998 3725   .453  ...  2.7  5.5  8.1  1.5  1.0  0.3  0.8  1.9
              1999 4283   .422  ...  1.6  2.9  4.6  0.5  0.6  0.2  0.4  1.4
              2000 4811   .447  ...  2.0  4.0  5.9  1.0  0.6  0.2  0.6  1.5
              2001 5330   .444  ...  1.3  2.5  3.8  0.5  0.4  0.1  0.5  1.5
A.J. Bramlett 2000 4684   .190  ...  1.5  1.3  2.8  0.0  0.1  0.0  0.4  1.6
A.J. English  1991 127    .439  ...  0.9  1.2  2.1  2.5  0.4  0.2  1.6  1.8
              1992 597    .433  ...  0.9  1.2  2.1  1.8  0.4  0.1  1.1  2.0
A.J. Green    2023 19115  .424  ...  0.2  1.1  1.3  0.6  0.2  0.0  0.3  0.9
A.J. Guyton   2001 5333   .406  ...  0.3  0.8  1.1  1.9  0.3  0.2  0.7  1.1
              2002 5886   .361  ...  0.3  0.7  1.0  1.8  0.2  0.2  0.8  0.5
              2003 6393   .000  ...  0.0  0.0  0.0  1.0  0.5  0.0  0.5  0.0
A.J. Hammons  2017 14814  .405  ...  0.4  1.3  1.6  0.2  0.0  0.6  0.5  1.0
A.J. Lawson   2023 19259  .500  ...  0.4  1.0  1.4  0.1  0.1  0.0  0.2  0.7

                           PTS  Year
Player        Year
A.C. Green    1991 164     9.1  1991
              1992 633    13.6  1992
              1993 1092   12.8  1993
              1994 1579   14.7  1994
              1995 2067   11.2  1995
              1996 2563    7.5  1996
              1997 3138    7.2  1997
              1998 3725    7.3  1998
              1999 4283    4.9  1999
              2000 4811    5.0  2000
              2001 5330    4.5  2001
A.J. Bramlett 2000 4684    1.0  2000
A.J. English  1991 127     8.8  1991
              1992 597    10.9  1992
A.J. Green    2023 19115   4.4  2023
A.J. Guyton   2001 5333    6.0  2001
              2002 5886    5.4  2002
              2003 6393    0.0  2003
A.J. Hammons  2017 14814   2.2  2017
A.J. Lawson   2023 19259   3.7  2023

[20 rows x 30 columns]

In [164]:
players.index = players.index.droplevel()

In [165]:
players.index = players.index.droplevel()

In [166]:
players[players["Player"] == "Greg Anderson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,DEN,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
467,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
1412,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
1911,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
2381,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
2948,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
3541,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [167]:
combined = players.merge(mvps, how="outer", on= ["Player", "Year"])

In [168]:
combined.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN

In [169]:
combined[combined["Pts Won"] > 0]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
206,Al Jefferson,C,29,CHA,73,73,35.0,9.6,18.8,.509,...,2.1,0.9,1.1,1.7,2.4,21.8,2014,34.0,1250.0,0.027
360,Allen Iverson,PG,21,PHI,76,74,40.1,8.2,19.8,.416,...,7.5,2.1,0.3,4.4,3.1,23.5,1997,1.0,1150.0,0.001
362,Allen Iverson,SG,23,PHI,48,48,41.5,9.1,22.0,.412,...,4.6,2.3,0.1,3.5,2.0,26.8,1999,319.0,1180.0,0.270
363,Allen Iverson,SG,24,PHI,70,70,40.8,10.4,24.8,.421,...,4.7,2.1,0.1,3.3,2.3,28.4,2000,132.0,1210.0,0.109
364,Allen Iverson,SG,25,PHI,71,71,42.0,10.7,25.5,.420,...,4.6,2.5,0.3,3.3,2.1,31.1,2001,1121.0,1240.0,0.904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14689,Vince Carter,SF,23,TOR,82,82,38.1,9.6,20.7,.465,...,3.9,1.3,1.1,2.2,3.2,25.7,2000,51.0,1210.0,0.042
14690,Vince Carter,SF,24,TOR,75,75,39.7,10.2,22.1,.460,...,3.9,1.5,1.1,2.2,2.7,27.6,2001,7.0,1240.0,0.006
14694,Vince Carter,SF-SG,28,NJN,77,76,36.7,9.0,20.0,.452,...,4.2,1.4,0.6,2.2,3.2,24.5,2005,3.0,1270.0,0.002
15082,Yao Ming,C,23,HOU,82,82,32.8,6.5,12.5,.522,...,1.5,0.3,1.9,2.5,3.3,17.5,2004,1.0,1230.0,0.001
15087,Yao Ming,C,28,HOU,77,77,33.6,7.4,13.4,.548,...,1.8,0.4,1.9,3.0,3.3,19.7,2009,1.0,1210.0,0.001

In [170]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [171]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15231,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
15232,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
15233,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0
15234,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
15235,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [172]:
teams = pd.read_csv("teams.csv")

In [173]:
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1098,13,51,31,.622,—,116.9,113.0,3.60,2023,Memphis Grizzlies* (2)
1099,14,42,40,.512,9.0,114.4,112.5,1.63,2023,New Orleans Pelicans* (9)
1100,15,38,44,.463,13.0,114.2,114.1,-0.14,2023,Dallas Mavericks (11)
1101,16,22,60,.268,29.0,110.7,118.6,-7.62,2023,Houston Rockets (14)
1102,17,22,60,.268,29.0,113.0,123.1,-9.82,2023,San Antonio Spurs (15)

In [174]:
teams = teams[~teams["W"].str.contains("Division")]

In [175]:
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)

/var/folders/_p/r9t1b6hj7vg3m_0qb667zd7w0000gn/T/ipykernel_20640/3338997264.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teams["Team"] = teams["Team"].str.replace("*", "", regex=False)

In [176]:
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1098,13,51,31,.622,—,116.9,113.0,3.60,2023,Memphis Grizzlies (2)
1099,14,42,40,.512,9.0,114.4,112.5,1.63,2023,New Orleans Pelicans (9)
1100,15,38,44,.463,13.0,114.2,114.1,-0.14,2023,Dallas Mavericks (11)
1101,16,22,60,.268,29.0,110.7,118.6,-7.62,2023,Houston Rockets (14)
1102,17,22,60,.268,29.0,113.0,123.1,-9.82,2023,San Antonio Spurs (15)

In [177]:
teams["Team"] = teams["Team"].str.replace("\(\d+\)", "", regex=True)

/var/folders/_p/r9t1b6hj7vg3m_0qb667zd7w0000gn/T/ipykernel_20640/1612970114.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teams["Team"] = teams["Team"].str.replace("\(\d+\)", "", regex=True)

In [178]:
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1098,13,51,31,.622,—,116.9,113.0,3.60,2023,Memphis Grizzlies
1099,14,42,40,.512,9.0,114.4,112.5,1.63,2023,New Orleans Pelicans
1100,15,38,44,.463,13.0,114.2,114.1,-0.14,2023,Dallas Mavericks
1101,16,22,60,.268,29.0,110.7,118.6,-7.62,2023,Houston Rockets
1102,17,22,60,.268,29.0,113.0,123.1,-9.82,2023,San Antonio Spurs

In [179]:
nicknames = {}

with open("nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev, name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

In [180]:
combined["Team"] = combined["Tm"].map(nicknames)

In [181]:
combined.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0,Los Angeles Lakers
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0,Phoenix Suns
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0,Phoenix Suns

In [182]:
stats = combined.merge(teams, how="outer", on=["Team", "Year"])

In [183]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Share,Team,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Memphis Grizzlies,13.0,51,31,.622,—,116.9,113.0,3.60
15262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,New Orleans Pelicans,14.0,42,40,.512,9.0,114.4,112.5,1.63
15263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Dallas Mavericks,15.0,38,44,.463,13.0,114.2,114.1,-0.14
15264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Houston Rockets,16.0,22,60,.268,29.0,110.7,118.6,-7.62
15265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,San Antonio Spurs,17.0,22,60,.268,29.0,113.0,123.1,-9.82

In [184]:
stats = stats.drop(stats[stats['Year'] == 2023].index)

In [185]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Share,Team,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15231,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,.484,...,0.0,Milwaukee Bucks,7.0,42,40,.512,9.0,103.6,103.8,-0.45
15232,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,.286,...,0.0,Milwaukee Bucks,7.0,42,40,.512,9.0,103.6,103.8,-0.45
15233,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,.470,...,0.0,Milwaukee Bucks,7.0,42,40,.512,9.0,103.6,103.8,-0.45
15234,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,.459,...,0.0,Milwaukee Bucks,7.0,42,40,.512,9.0,103.6,103.8,-0.45
15235,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,.455,...,0.0,Milwaukee Bucks,7.0,42,40,.512,9.0,103.6,103.8,-0.45

In [186]:
del stats["Unnamed: 0"]

In [188]:
stats.dtypes

Player      object
Pos         object
Age         object
Tm          object
G           object
GS          object
MP          object
FG          object
FGA         object
FG%         object
3P          object
3PA         object
3P%         object
2P          object
2PA         object
2P%         object
eFG%        object
FT          object
FTA         object
FT%         object
ORB         object
DRB         object
TRB         object
AST         object
STL         object
BLK         object
TOV         object
PF          object
PTS         object
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W           object
L           object
W/L%        object
GB          object
PS/G        object
PA/G        object
SRS         object
dtype: object